version: "3.8"

services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - zeroim

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    networks:
      - zeroim

  etcd:
    image: gcr.io/etcd-development/etcd:latest
    container_name: etcd
    command: >
      /usr/local/bin/etcd
      --name etcd-server
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://0.0.0.0:2380
      --initial-cluster etcd-server=http://0.0.0.0:2380
      --initial-cluster-token etcd-cluster-1
      --initial-cluster-state new
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - zeroim

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - zeroim

networks:
  zeroim:
    driver: bridge
