// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: imrpc.proto

package server

import (
	"context"

	"zeroim/imrpc/imrpc"
	"zeroim/imrpc/internal/logic"
	"zeroim/imrpc/internal/svc"
)

type ImrpcServer struct {
	svcCtx *svc.ServiceContext
	imrpc.UnimplementedImrpcServer
}

func NewImrpcServer(svcCtx *svc.ServiceContext) *ImrpcServer {
	return &ImrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *ImrpcServer) Login(ctx context.Context, in *imrpc.LoginRequest) (*imrpc.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *ImrpcServer) Logout(ctx context.Context, in *imrpc.LogoutRequest) (*imrpc.LogoutResponse, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}
