// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: edge.proto

package server

import (
	"context"

	"zeroim/edge/edge"
	"zeroim/edge/internal/svc"
)

type EdgeServer struct {
	svcCtx *svc.ServiceContext
	edge.UnimplementedEdgeServer
}

func NewEdgeServer(svcCtx *svc.ServiceContext) *EdgeServer {
	return &EdgeServer{
		svcCtx: svcCtx,
	}
}

func (s *EdgeServer) Ping(ctx context.Context, in *edge.Request) (*edge.Response, error) {
	// l := logic.NewMqLogic(ctx, s.svcCtx)
	// return l.Ping(in)
	return nil, nil
}
